function findTheDifference(s: string, t: string): string {
    /**
     * Problem: 
     * You are given two strings s and t.
     * String t is generated by shuffling string s and then adding ONE extra letter at a random position.
     * Return the letter that was added to t.
     * 
     * Example:
     * s = "abcd", t = "abcde" → Output: "e"
     * s = "a", t = "aa" → Output: "a"
     */

    // Approach: Use a frequency map (HashMap) to count characters
    // 1. Count frequency of all characters in t
    // 2. Subtract frequency of characters in s
    // 3. The character with count = 1 is the extra one

    const map: Map<string, number> = new Map();

    // Step 1: Count frequency of each character in t
    for (let i = 0; i < t.length; i++) {
        const char = t[i];
        map.set(char, (map.get(char) ?? 0) + 1);
    }

    // Step 2: Subtract frequency of characters present in s
    // Since t = s + 1 extra char, all common characters will have count reduced
    for (let i = 0; i < s.length; i++) {
        const char = s[i];
        // Use non-null assertion (!) because we know the char exists in map
        map.set(char, map.get(char)! - 1);
    }

    // Step 3: Find the character that has count = 1 (the extra one)
    // All other characters will have count = 0
    for (const [char, count] of map) {
        if (count === 1) {
            return char;
        }
    }

    // This line should never be reached if input follows problem constraints
    return "";
}